### ISSUE TITLE
Vulnerability: protobufjs

### ISSUE THREAD

**Issue by julianna-ciq** [gherkin-lint/gherkin-lint#289]
We use gherkin-lint, and out security scans have started showing this message:

>└─ protobufjs: 6.11.3
>   ├─ ID: 1092429
>   ├─ Issue: protobufjs Prototype Pollution vulnerability
>   ├─ URL: https://github.com/advisories/GHSA-h755-8qp9-cq85
>   ├─ Severity: high
>   ├─ Vulnerable Versions: >=6.10.0 <7.2.4
>   ├─ Patched Versions: >=7.2.4
>   ├─ Via: gherkin-lint
>   └─ Recommendation: Upgrade to version 7.2.4 or later

For reference, it appears that this is where protobufjs is in the dependency tree:
>protobufjs@6.11.3
>node_modules/protobufjs
>  protobufjs@"^6.8.8" from cucumber-messages@8.0.0
>  node_modules/cucumber-messages
>>  cucumber-messages@"8.0.0" from gherkin@9.0.0
>>>  node_modules/gherkin
>>>>    gherkin@"9.0.0" from gherkin-lint@4.2.2
>>>>>    node_modules/gherkin-lint
>>>>>>     gherkin-lint@"4.2.2" from the root project

It looks like the repo `gherkin` has been deprecated in favor of `@cucumber/gherkin`, which does not seem to have the vulnerability in its dependency tree.

Is it possible for gherkin-lint to update its dependencies to remove any vulnerable versions?

**Comment by andrewnicols** [comment]
I'll be rolling a release containing this update in the coming week or two when I get access to roll releases. As the dependabot change has already landed for this, I'm going to close this issue.
