### ISSUE TITLE
Is this project being maintained or is it DEAD? 

### ISSUE THREAD

**Issue by NutriMarc** [gherkin-lint/gherkin-lint#293]
@vsiakka Are you still maintaining this repo? Please respond to this ping if you are.

I noticed numerous issues and PR reviews that don't have a response. I feel this code is valuable and worth maintaining but contributions are blocked without your approvals. Considering forking this and pulling people in to get it going, BUT ONLY IF you are no longer maintaining or watching this repository.

**Comment by NutriMarc** [comment]
Role-call for any possible contributors. Should we fork this repo and update this code for 2023? Of course we will wait on @vsiakka response.

@andrewnicols
@justinvos
@raspe88
@jimmyko

**Comment by jimmyko** [comment]
I'm happy to fork it and I also don't mind being the volunteer to be the maintainer.

**Comment by vsiakka** [comment]
Hello, i am the owner of the repo. I haven't made any changes in the past 3 years and I don't think I'll be able to make any in the foreseeable future, so I am happy to add other maintainers and take any actions to make creating new releases possible. 
I'll be available in the middle of October to do a hand off, so let's setup a date meet and walk me through the buttons I have to click :)

**Comment by andrewnicols** [comment]
Hi folks,

I contacted Vasiliki recently to see if we could get things moving.

What I would suggest is:
- grant myself admin access to this repo
- I'll create a new gherkin-lint organisation
- I'll _move_ this repository to that organisation
- I'll then add others (@jimmyko, and any other interested people)
- Update the npmjs repository to add new maintainers
- Update the npmjs repository to point to the new repo location
- Update coveralls configuration to point to the new repo
- set coveralls config in github secrets

Once we've done that administration:
- merge #292 to ditch Travis and add support for GHA
- update all dependabot changes and merge all those that are correct
- roll a new minor release
- merge new features issues like #244 and #248, and any others
- roll a new major (semver release)

How does that sound?

**Comment by andrewnicols** [comment]
Closing as being tracked in #294
